/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    staff: StaffAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    legal: Legal;
    media: Media;
    staff: Staff;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    legal: LegalSelect<false> | LegalSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    staff: StaffSelect<false> | StaffSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale:
    ('false' | 'none' | 'null') | false | null | ('bw' | 'za' | 'zw' | 'global') | ('bw' | 'za' | 'zw' | 'global')[];
  globals: {
    header: Header;
    footer: Footer;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: 'bw' | 'za' | 'zw' | 'global';
  widgets: {
    collections: CollectionsWidget;
  };
  user: Staff;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface StaffAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Each market's version is a language in the switcher at the top. A market without its own words shows Botswana's.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  /**
   * The page's name in the editor, and its title unless the search title below says otherwise.
   */
  title: string;
  /**
   * home is the market's home page, pricing and security are those pages. Anything else becomes /<market>/<address>, e.g. about.
   */
  slug: string;
  /**
   * Landing: full-width sections. Document: one column of headings and text, like the Security page.
   */
  style?: ('landing' | 'document') | null;
  layout?:
    | (
        | PageIntroBlock
        | HeroBlock
        | DomainSearchBlock
        | FeatureCardsBlock
        | ServicesGridBlock
        | PricingBlock
        | TextBlock
        | ImageTextBlock
        | FaqBlock
        | TestimonialsBlock
        | LogoStripBlock
        | CallToActionBlock
        | AssistantNoticeBlock
      )[]
    | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PageIntroBlock".
 */
export interface PageIntroBlock {
  kicker?: string | null;
  /**
   * The page's main heading.
   */
  heading: string;
  intro?: string | null;
  showTaxNote?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'pageIntro';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock".
 */
export interface HeroBlock {
  kicker?: string | null;
  /**
   * The page's main heading. Keep it short.
   */
  heading: string;
  sub?: string | null;
  primary?: {
    label?: string | null;
    to?: ('market' | 'site' | 'email') | null;
    /**
     * Starts with /. For this market's pricing page: /pricing
     */
    path?: string | null;
    subject?: string | null;
  };
  secondary?: {
    label?: string | null;
    to?: ('market' | 'site' | 'email') | null;
    /**
     * Starts with /. For this market's pricing page: /pricing
     */
    path?: string | null;
    subject?: string | null;
  };
  supporting?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  picture: {
    source: 'upload' | 'console-home' | 'console-invoice' | 'thebe-approvals';
    image?: (number | null) | Media;
    caption?: string | null;
  };
  domainSearch?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * What the image shows, for people who can't see it. Describe it in a short sentence.
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    share?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DomainSearchBlock".
 */
export interface DomainSearchBlock {
  heading?: string | null;
  intro?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'domainSearch';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeatureCardsBlock".
 */
export interface FeatureCardsBlock {
  kicker?: string | null;
  heading: string;
  intro?: string | null;
  tone: 'plain' | 'light' | 'dark';
  style: 'raised' | 'flat';
  items?:
    | {
        icon:
          | 'users'
          | 'credit-card'
          | 'life-buoy'
          | 'shield-check'
          | 'mail'
          | 'server'
          | 'lock'
          | 'hard-drive'
          | 'layout-grid'
          | 'boxes'
          | 'sparkles'
          | 'graduation-cap'
          | 'building'
          | 'trending-up'
          | 'handshake'
          | 'globe'
          | 'earth'
          | 'check'
          | 'receipt';
        title: string;
        body?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'featureCards';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ServicesGridBlock".
 */
export interface ServicesGridBlock {
  kicker?: string | null;
  heading: string;
  intro?: string | null;
  tone: 'plain' | 'light' | 'dark';
  /**
   * Optional. Lets a link jump here, e.g. services for /bw#services.
   */
  anchor?: string | null;
  showTaxNote?: boolean | null;
  cards?:
    | {
        icon:
          | 'users'
          | 'credit-card'
          | 'life-buoy'
          | 'shield-check'
          | 'mail'
          | 'server'
          | 'lock'
          | 'hard-drive'
          | 'layout-grid'
          | 'boxes'
          | 'sparkles'
          | 'graduation-cap'
          | 'building'
          | 'trending-up'
          | 'handshake'
          | 'globe'
          | 'earth'
          | 'check'
          | 'receipt';
        title: string;
        body?: string | null;
        note?: string | null;
        dataCentre?: boolean | null;
        /**
         * Tick categories or single products. The lowest live price among them shows in each market.
         */
        products?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  more?: {
    label?: string | null;
    to?: ('market' | 'site' | 'email') | null;
    /**
     * Starts with /. For this market's pricing page: /pricing
     */
    path?: string | null;
    subject?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'servicesGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PricingBlock".
 */
export interface PricingBlock {
  kicker?: string | null;
  heading: string;
  intro?: string | null;
  tone: 'plain' | 'light' | 'dark';
  /**
   * Tick categories or single products. The lowest live price among them shows in each market.
   */
  products?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  more?: {
    label?: string | null;
    to?: ('market' | 'site' | 'email') | null;
    /**
     * Starts with /. For this market's pricing page: /pricing
     */
    path?: string | null;
    subject?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'pricing';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TextBlock".
 */
export interface TextBlock {
  heading?: string | null;
  /**
   * You can write {market}, {support-email}, {data-protection-law} or {deletion-notice-days}; the market's own details appear in their place.
   */
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  tone: 'plain' | 'light' | 'dark';
  id?: string | null;
  blockName?: string | null;
  blockType: 'text';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageTextBlock".
 */
export interface ImageTextBlock {
  kicker?: string | null;
  heading: string;
  intro?: string | null;
  tone: 'plain' | 'light' | 'dark';
  points?:
    | {
        icon:
          | 'users'
          | 'credit-card'
          | 'life-buoy'
          | 'shield-check'
          | 'mail'
          | 'server'
          | 'lock'
          | 'hard-drive'
          | 'layout-grid'
          | 'boxes'
          | 'sparkles'
          | 'graduation-cap'
          | 'building'
          | 'trending-up'
          | 'handshake'
          | 'globe'
          | 'earth'
          | 'check'
          | 'receipt';
        title: string;
        body?: string | null;
        id?: string | null;
      }[]
    | null;
  picture: {
    source: 'upload' | 'console-home' | 'console-invoice' | 'thebe-approvals';
    image?: (number | null) | Media;
    caption?: string | null;
  };
  pictureSide: 'right' | 'left';
  /**
   * Optional. Puts the picture in a card with a title, a line and a link.
   */
  card?: {
    kicker?: string | null;
    title?: string | null;
    body?: string | null;
    link?: {
      label?: string | null;
      to?: ('market' | 'site' | 'email') | null;
      /**
       * Starts with /. For this market's pricing page: /pricing
       */
      path?: string | null;
      subject?: string | null;
    };
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'imageText';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FaqBlock".
 */
export interface FaqBlock {
  kicker?: string | null;
  heading: string;
  intro?: string | null;
  tone: 'plain' | 'light' | 'dark';
  items?:
    | {
        question: string;
        answer: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'faq';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialsBlock".
 */
export interface TestimonialsBlock {
  /**
   * Hidden from view (read by screen readers) when left empty.
   */
  heading?: string | null;
  tone: 'plain' | 'light' | 'dark';
  /**
   * Real customers only, with their permission. The section stays hidden while there are none.
   */
  items?:
    | {
        quote: string;
        name: string;
        role?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'testimonials';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LogoStripBlock".
 */
export interface LogoStripBlock {
  heading?: string | null;
  tone: 'plain' | 'light' | 'dark';
  logos?:
    | {
        name: string;
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'logoStrip';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock".
 */
export interface CallToActionBlock {
  heading: string;
  body?: string | null;
  tone: 'plain' | 'light' | 'dark';
  primary?: {
    label?: string | null;
    to?: ('market' | 'site' | 'email') | null;
    /**
     * Starts with /. For this market's pricing page: /pricing
     */
    path?: string | null;
    subject?: string | null;
  };
  secondary?: {
    label?: string | null;
    to?: ('market' | 'site' | 'email') | null;
    /**
     * Starts with /. For this market's pricing page: /pricing
     */
    path?: string | null;
    subject?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'callToAction';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AssistantNoticeBlock".
 */
export interface AssistantNoticeBlock {
  /**
   * The notice itself is a fixed product fact: what the support assistant is sent, and where the AI service runs.
   */
  heading: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'assistantNotice';
}
/**
 * Each market's text is a language in the switcher at the top. A market without its own text shows a note that it is on its way, never another market's.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal".
 */
export interface Legal {
  id: number;
  /**
   * Data protection shows on the Security page.
   */
  kind: 'terms' | 'privacy' | 'refunds' | 'service-providers' | 'data-protection';
  title: string;
  /**
   * e.g. Last updated: 29 September 2026
   */
  updated?: string | null;
  /**
   * Shown at the top until the text is approved by legal.
   */
  draftNotice?: string | null;
  /**
   * Only a Publisher can tick this, once a lawyer has approved this market's text. It removes the draft banner when published.
   */
  approvedByLegal?: boolean | null;
  /**
   * You can write {market}, {support-email}, {data-protection-law} or {deletion-notice-days}; the market's own details appear in their place.
   */
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Website roles are set on the Staff page in the staff console.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "staff".
 */
export interface Staff {
  id: number;
  consoleUserId: string;
  name: string;
  email: string;
  websiteRole: 'EDITOR' | 'PUBLISHER';
  updatedAt: string;
  createdAt: string;
  collection: 'staff';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'legal';
        value: number | Legal;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'staff';
        value: number | Staff;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'staff';
    value: number | Staff;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'staff';
    value: number | Staff;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  style?: T;
  layout?:
    | T
    | {
        pageIntro?: T | PageIntroBlockSelect<T>;
        hero?: T | HeroBlockSelect<T>;
        domainSearch?: T | DomainSearchBlockSelect<T>;
        featureCards?: T | FeatureCardsBlockSelect<T>;
        servicesGrid?: T | ServicesGridBlockSelect<T>;
        pricing?: T | PricingBlockSelect<T>;
        text?: T | TextBlockSelect<T>;
        imageText?: T | ImageTextBlockSelect<T>;
        faq?: T | FaqBlockSelect<T>;
        testimonials?: T | TestimonialsBlockSelect<T>;
        logoStrip?: T | LogoStripBlockSelect<T>;
        callToAction?: T | CallToActionBlockSelect<T>;
        assistantNotice?: T | AssistantNoticeBlockSelect<T>;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PageIntroBlock_select".
 */
export interface PageIntroBlockSelect<T extends boolean = true> {
  kicker?: T;
  heading?: T;
  intro?: T;
  showTaxNote?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock_select".
 */
export interface HeroBlockSelect<T extends boolean = true> {
  kicker?: T;
  heading?: T;
  sub?: T;
  primary?:
    | T
    | {
        label?: T;
        to?: T;
        path?: T;
        subject?: T;
      };
  secondary?:
    | T
    | {
        label?: T;
        to?: T;
        path?: T;
        subject?: T;
      };
  supporting?:
    | T
    | {
        text?: T;
        id?: T;
      };
  picture?:
    | T
    | {
        source?: T;
        image?: T;
        caption?: T;
      };
  domainSearch?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DomainSearchBlock_select".
 */
export interface DomainSearchBlockSelect<T extends boolean = true> {
  heading?: T;
  intro?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeatureCardsBlock_select".
 */
export interface FeatureCardsBlockSelect<T extends boolean = true> {
  kicker?: T;
  heading?: T;
  intro?: T;
  tone?: T;
  style?: T;
  items?:
    | T
    | {
        icon?: T;
        title?: T;
        body?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ServicesGridBlock_select".
 */
export interface ServicesGridBlockSelect<T extends boolean = true> {
  kicker?: T;
  heading?: T;
  intro?: T;
  tone?: T;
  anchor?: T;
  showTaxNote?: T;
  cards?:
    | T
    | {
        icon?: T;
        title?: T;
        body?: T;
        note?: T;
        dataCentre?: T;
        products?: T;
        id?: T;
      };
  more?:
    | T
    | {
        label?: T;
        to?: T;
        path?: T;
        subject?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PricingBlock_select".
 */
export interface PricingBlockSelect<T extends boolean = true> {
  kicker?: T;
  heading?: T;
  intro?: T;
  tone?: T;
  products?: T;
  more?:
    | T
    | {
        label?: T;
        to?: T;
        path?: T;
        subject?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TextBlock_select".
 */
export interface TextBlockSelect<T extends boolean = true> {
  heading?: T;
  body?: T;
  tone?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageTextBlock_select".
 */
export interface ImageTextBlockSelect<T extends boolean = true> {
  kicker?: T;
  heading?: T;
  intro?: T;
  tone?: T;
  points?:
    | T
    | {
        icon?: T;
        title?: T;
        body?: T;
        id?: T;
      };
  picture?:
    | T
    | {
        source?: T;
        image?: T;
        caption?: T;
      };
  pictureSide?: T;
  card?:
    | T
    | {
        kicker?: T;
        title?: T;
        body?: T;
        link?:
          | T
          | {
              label?: T;
              to?: T;
              path?: T;
              subject?: T;
            };
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FaqBlock_select".
 */
export interface FaqBlockSelect<T extends boolean = true> {
  kicker?: T;
  heading?: T;
  intro?: T;
  tone?: T;
  items?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialsBlock_select".
 */
export interface TestimonialsBlockSelect<T extends boolean = true> {
  heading?: T;
  tone?: T;
  items?:
    | T
    | {
        quote?: T;
        name?: T;
        role?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LogoStripBlock_select".
 */
export interface LogoStripBlockSelect<T extends boolean = true> {
  heading?: T;
  tone?: T;
  logos?:
    | T
    | {
        name?: T;
        image?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock_select".
 */
export interface CallToActionBlockSelect<T extends boolean = true> {
  heading?: T;
  body?: T;
  tone?: T;
  primary?:
    | T
    | {
        label?: T;
        to?: T;
        path?: T;
        subject?: T;
      };
  secondary?:
    | T
    | {
        label?: T;
        to?: T;
        path?: T;
        subject?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AssistantNoticeBlock_select".
 */
export interface AssistantNoticeBlockSelect<T extends boolean = true> {
  heading?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal_select".
 */
export interface LegalSelect<T extends boolean = true> {
  kind?: T;
  title?: T;
  updated?: T;
  draftNotice?: T;
  approvedByLegal?: T;
  body?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        share?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "staff_select".
 */
export interface StaffSelect<T extends boolean = true> {
  consoleUserId?: T;
  name?: T;
  email?: T;
  websiteRole?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * The menu at the top of every public page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  /**
   * The five service families in the Services menu. The first link is where a phone's menu goes.
   */
  groups?:
    | {
        icon:
          | 'users'
          | 'credit-card'
          | 'life-buoy'
          | 'shield-check'
          | 'mail'
          | 'server'
          | 'lock'
          | 'hard-drive'
          | 'layout-grid'
          | 'boxes'
          | 'sparkles'
          | 'graduation-cap'
          | 'building'
          | 'trending-up'
          | 'handshake'
          | 'globe'
          | 'earth'
          | 'check'
          | 'receipt';
        title: string;
        blurb?: string | null;
        links?:
          | {
              link: {
                label: string;
                to?: ('market' | 'site' | 'email') | null;
                /**
                 * Starts with /. For this market's pricing page: /pricing
                 */
                path?: string | null;
                subject?: string | null;
              };
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  menuNote?: string | null;
  menuLink?: {
    label?: string | null;
    to?: ('market' | 'site' | 'email') | null;
    /**
     * Starts with /. For this market's pricing page: /pricing
     */
    path?: string | null;
    subject?: string | null;
  };
  pages?:
    | {
        link: {
          label: string;
          to?: ('market' | 'site' | 'email') | null;
          /**
           * Starts with /. For this market's pricing page: /pricing
           */
          path?: string | null;
          subject?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The links and words at the bottom of every public page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  tagline?: string | null;
  columns?:
    | {
        heading: string;
        links?:
          | {
              link: {
                label: string;
                to?: ('market' | 'site' | 'email') | null;
                /**
                 * Starts with /. For this market's pricing page: /pricing
                 */
                path?: string | null;
                subject?: string | null;
              };
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  contactHeading?: string | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  groups?:
    | T
    | {
        icon?: T;
        title?: T;
        blurb?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    label?: T;
                    to?: T;
                    path?: T;
                    subject?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  menuNote?: T;
  menuLink?:
    | T
    | {
        label?: T;
        to?: T;
        path?: T;
        subject?: T;
      };
  pages?:
    | T
    | {
        link?:
          | T
          | {
              label?: T;
              to?: T;
              path?: T;
              subject?: T;
            };
        id?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  tagline?: T;
  columns?:
    | T
    | {
        heading?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    label?: T;
                    to?: T;
                    path?: T;
                    subject?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  contactHeading?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'legal';
          value: number | Legal;
        } | null);
    global?: string | null;
    user?: {
      relationTo: 'staff';
      value: number | Staff;
    } | null;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}