/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    staff: StaffAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    insights: Insight;
    help: Help;
    legal: Legal;
    partners: Partner;
    'client-logos': ClientLogo;
    'proof-numbers': ProofNumber;
    'team-members': TeamMember;
    testimonials: Testimonial;
    'showcase-sites': ShowcaseSite;
    media: Media;
    staff: Staff;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    insights: InsightsSelect<false> | InsightsSelect<true>;
    help: HelpSelect<false> | HelpSelect<true>;
    legal: LegalSelect<false> | LegalSelect<true>;
    partners: PartnersSelect<false> | PartnersSelect<true>;
    'client-logos': ClientLogosSelect<false> | ClientLogosSelect<true>;
    'proof-numbers': ProofNumbersSelect<false> | ProofNumbersSelect<true>;
    'team-members': TeamMembersSelect<false> | TeamMembersSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    'showcase-sites': ShowcaseSitesSelect<false> | ShowcaseSitesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    staff: StaffSelect<false> | StaffSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale:
    ('false' | 'none' | 'null') | false | null | ('bw' | 'za' | 'zw' | 'global') | ('bw' | 'za' | 'zw' | 'global')[];
  globals: {
    header: Header;
    footer: Footer;
    announcement: Announcement;
    'sales-assistant': SalesAssistant;
    'partner-links': PartnerLink;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    announcement: AnnouncementSelect<false> | AnnouncementSelect<true>;
    'sales-assistant': SalesAssistantSelect<false> | SalesAssistantSelect<true>;
    'partner-links': PartnerLinksSelect<false> | PartnerLinksSelect<true>;
  };
  locale: 'bw' | 'za' | 'zw' | 'global';
  widgets: {
    collections: CollectionsWidget;
  };
  user: Staff;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface StaffAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Each market's version is a language in the switcher at the top. A market without its own words shows Botswana's.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  /**
   * The page's name in the editor, and its title unless the search title below says otherwise.
   */
  title: string;
  /**
   * home is the market's home page; pricing, security and quote are those pages. Anything else becomes /<market>/<address>, e.g. about.
   */
  slug: string;
  /**
   * Landing: full-width sections. Document: one column of headings and text, like the Security page.
   */
  style?: ('landing' | 'document') | null;
  layout?:
    | (
        | HomeHeroBlock
        | DomainStoreBlock
        | ProofStripBlock
        | NumberedServicesBlock
        | WhoWeHelpBlock
        | EmailShowcaseBlock
        | WebsitesShowcaseBlock
        | SecurityPanelBlock
        | ThebeSectionBlock
        | PlansTableBlock
        | CompareTableBlock
        | TeamSectionBlock
        | ClosingBannerBlock
        | PageIntroBlock
        | HeroBlock
        | DomainSearchBlock
        | FeatureCardsBlock
        | ServicesGridBlock
        | PricingBlock
        | PriceTablesBlock
        | TextBlock
        | ImageTextBlock
        | FaqBlock
        | TestimonialsBlock
        | LogoStripBlock
        | InsightsStripBlock
        | CallToActionBlock
        | AssistantNoticeBlock
      )[]
    | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HomeHeroBlock".
 */
export interface HomeHeroBlock {
  kicker?: string | null;
  heading: string;
  sub?: string | null;
  /**
   * Optional. Phones show these instead.
   */
  subPhone?: string | null;
  /**
   * Under the headline, and the start of the page's search description unless one is set under Search and sharing.
   */
  supporting?: string | null;
  primary?: {
    label?: string | null;
    to?: ('market' | 'site' | 'email' | 'thebe') | null;
    /**
     * Starts with /. For this market's pricing page: /pricing
     */
    path?: string | null;
    subject?: string | null;
  };
  secondary?: {
    label?: string | null;
    to?: ('market' | 'site' | 'email' | 'thebe') | null;
    /**
     * Starts with /. For this market's pricing page: /pricing
     */
    path?: string | null;
    subject?: string | null;
  };
  showConsole?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'homeHero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DomainStoreBlock".
 */
export interface DomainStoreBlock {
  /**
   * Optional. Lets a link jump here, e.g. domains for /bw#domains.
   */
  anchor?: string | null;
  kicker?: string | null;
  heading: string;
  /**
   * Optional. Phones show these instead.
   */
  headingPhone?: string | null;
  intro?: string | null;
  /**
   * Optional. Phones show these instead; left empty, phones show no introduction, as designed.
   */
  introPhone?: string | null;
  example?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'domainStore';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProofStripBlock".
 */
export interface ProofStripBlock {
  /**
   * Optional. Lets a link jump here, e.g. domains for /bw#domains.
   */
  anchor?: string | null;
  numbers?: boolean | null;
  partnersHeading?: string | null;
  clientsHeading?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'proofStrip';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "NumberedServicesBlock".
 */
export interface NumberedServicesBlock {
  /**
   * Optional. Lets a link jump here, e.g. domains for /bw#domains.
   */
  anchor?: string | null;
  kicker?: string | null;
  heading: string;
  /**
   * Optional. Phones show these instead.
   */
  headingPhone?: string | null;
  items?:
    | {
        title: string;
        body?: string | null;
        /**
         * Optional. Phones show these instead.
         */
        bodyPhone?: string | null;
        link?: {
          label?: string | null;
          to?: ('market' | 'site' | 'email' | 'thebe') | null;
          /**
           * Starts with /. For this market's pricing page: /pricing
           */
          path?: string | null;
          subject?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'numberedServices';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WhoWeHelpBlock".
 */
export interface WhoWeHelpBlock {
  /**
   * Optional. Lets a link jump here, e.g. domains for /bw#domains.
   */
  anchor?: string | null;
  kicker?: string | null;
  heading: string;
  /**
   * Optional. Phones show these instead.
   */
  headingPhone?: string | null;
  intro?: string | null;
  /**
   * Optional. Phones show these instead; left empty, phones show no introduction, as designed.
   */
  introPhone?: string | null;
  /**
   * The first is the main customer and is drawn larger.
   */
  items?:
    | {
        title: string;
        body?: string | null;
        /**
         * Optional. Phones show these instead.
         */
        bodyPhone?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * The section stays hidden until this is ticked. Only Publishers can change this.
   */
  approved?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'whoWeHelp';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EmailShowcaseBlock".
 */
export interface EmailShowcaseBlock {
  /**
   * Optional. Lets a link jump here, e.g. domains for /bw#domains.
   */
  anchor?: string | null;
  kicker?: string | null;
  heading: string;
  /**
   * Optional. Phones show these instead.
   */
  headingPhone?: string | null;
  intro?: string | null;
  /**
   * Optional. Phones show these instead; left empty, phones show no introduction, as designed.
   */
  introPhone?: string | null;
  caption?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'emailShowcase';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WebsitesShowcaseBlock".
 */
export interface WebsitesShowcaseBlock {
  /**
   * Optional. Lets a link jump here, e.g. domains for /bw#domains.
   */
  anchor?: string | null;
  kicker?: string | null;
  heading: string;
  /**
   * Optional. Phones show these instead.
   */
  headingPhone?: string | null;
  intro?: string | null;
  /**
   * Optional. Phones show these instead; left empty, phones show no introduction, as designed.
   */
  introPhone?: string | null;
  cards?:
    | {
        title: string;
        body?: string | null;
        /**
         * Optional. Phones show these instead.
         */
        bodyPhone?: string | null;
        link?: {
          label?: string | null;
          to?: ('market' | 'site' | 'email' | 'thebe') | null;
          /**
           * Starts with /. For this market's pricing page: /pricing
           */
          path?: string | null;
          subject?: string | null;
        };
        /**
         * Optional. Tick the products this is about: it shows only while one of them is live and priced in the market.
         */
        products?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  industries?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'websitesShowcase';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SecurityPanelBlock".
 */
export interface SecurityPanelBlock {
  /**
   * Optional. Lets a link jump here, e.g. domains for /bw#domains.
   */
  anchor?: string | null;
  kicker?: string | null;
  heading: string;
  /**
   * Optional. Phones show these instead.
   */
  headingPhone?: string | null;
  intro?: string | null;
  /**
   * Optional. Phones show these instead; left empty, phones show no introduction, as designed.
   */
  introPhone?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'securityPanel';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ThebeSectionBlock".
 */
export interface ThebeSectionBlock {
  /**
   * Optional. Lets a link jump here, e.g. domains for /bw#domains.
   */
  anchor?: string | null;
  kicker?: string | null;
  heading: string;
  /**
   * Optional. Phones show these instead.
   */
  headingPhone?: string | null;
  intro?: string | null;
  /**
   * Optional. Phones show these instead; left empty, phones show no introduction, as designed.
   */
  introPhone?: string | null;
  /**
   * Optional. Phones show these instead.
   */
  kickerPhone?: string | null;
  features?:
    | {
        title: string;
        body?: string | null;
        /**
         * Shows only while the switch below is on.
         */
        accounting?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Leave off until those connections exist in Thebe. The accounting feature stays hidden while it is off.
   */
  showAccounting?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'thebeSection';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PlansTableBlock".
 */
export interface PlansTableBlock {
  /**
   * Optional. Lets a link jump here, e.g. domains for /bw#domains.
   */
  anchor?: string | null;
  kicker?: string | null;
  heading: string;
  /**
   * Optional. Phones show these instead.
   */
  headingPhone?: string | null;
  intro?: string | null;
  /**
   * Optional. Phones show these instead; left empty, phones show no introduction, as designed.
   */
  introPhone?: string | null;
  /**
   * Prices come from the price books: each plan's price per business and per user. The section hides until all three plans are on sale in the market.
   */
  rows?:
    | {
        label: string;
        labelPhone?: string | null;
        start?: string | null;
        startPhone?: string | null;
        startIncluded?: boolean | null;
        grow?: string | null;
        growPhone?: string | null;
        growIncluded?: boolean | null;
        protect?: string | null;
        protectPhone?: string | null;
        protectIncluded?: boolean | null;
        id?: string | null;
      }[]
    | null;
  footnote?: string | null;
  users?: number | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'plansTable';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CompareTableBlock".
 */
export interface CompareTableBlock {
  /**
   * Optional. Lets a link jump here, e.g. domains for /bw#domains.
   */
  anchor?: string | null;
  kicker?: string | null;
  heading: string;
  /**
   * Optional. Phones show these instead.
   */
  headingPhone?: string | null;
  freeHeading?: string | null;
  usHeading?: string | null;
  rows?:
    | {
        label: string;
        free: string;
        us: string;
        /**
         * Optional. Phones show these instead.
         */
        labelPhone?: string | null;
        /**
         * Optional. Phones show these instead.
         */
        freePhone?: string | null;
        /**
         * Optional. Phones show these instead.
         */
        usPhone?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'compareTable';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TeamSectionBlock".
 */
export interface TeamSectionBlock {
  /**
   * Optional. Lets a link jump here, e.g. domains for /bw#domains.
   */
  anchor?: string | null;
  kicker?: string | null;
  heading: string;
  /**
   * Optional. Phones show these instead.
   */
  headingPhone?: string | null;
  intro?: string | null;
  /**
   * Optional. Phones show these instead; left empty, phones show no introduction, as designed.
   */
  introPhone?: string | null;
  link?: {
    label?: string | null;
    to?: ('market' | 'site' | 'email' | 'thebe') | null;
    /**
     * Starts with /. For this market's pricing page: /pricing
     */
    path?: string | null;
    subject?: string | null;
  };
  /**
   * Links to NSMC's website, https://www.nsmc.africa.
   */
  nsmc?: {
    lead?: string | null;
    text?: string | null;
    /**
     * Optional. Phones show these instead.
     */
    leadPhone?: string | null;
    /**
     * Optional. Phones show these instead.
     */
    textPhone?: string | null;
    linkLabel?: string | null;
  };
  /**
   * Optional. Shown after the introduction once the last 90 days have at least 30 answered tickets; {time} becomes the median, e.g. 12 minutes.
   */
  replyLine?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'teamSection';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ClosingBannerBlock".
 */
export interface ClosingBannerBlock {
  heading: string;
  primary?: {
    label?: string | null;
    to?: ('market' | 'site' | 'email' | 'thebe') | null;
    /**
     * Starts with /. For this market's pricing page: /pricing
     */
    path?: string | null;
    subject?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'closingBanner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PageIntroBlock".
 */
export interface PageIntroBlock {
  kicker?: string | null;
  /**
   * The page's main heading.
   */
  heading: string;
  intro?: string | null;
  showTaxNote?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'pageIntro';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock".
 */
export interface HeroBlock {
  kicker?: string | null;
  /**
   * The page's main heading. Keep it short.
   */
  heading: string;
  sub?: string | null;
  primary?: {
    label?: string | null;
    to?: ('market' | 'site' | 'email' | 'thebe') | null;
    /**
     * Starts with /. For this market's pricing page: /pricing
     */
    path?: string | null;
    subject?: string | null;
  };
  secondary?: {
    label?: string | null;
    to?: ('market' | 'site' | 'email' | 'thebe') | null;
    /**
     * Starts with /. For this market's pricing page: /pricing
     */
    path?: string | null;
    subject?: string | null;
  };
  supporting?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  picture: {
    source: 'upload' | 'console-home' | 'console-invoice' | 'thebe-approvals';
    image?: (number | null) | Media;
    caption?: string | null;
  };
  domainSearch?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * What the image shows, for people who can't see it. Describe it in a short sentence.
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    share?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DomainSearchBlock".
 */
export interface DomainSearchBlock {
  heading?: string | null;
  intro?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'domainSearch';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeatureCardsBlock".
 */
export interface FeatureCardsBlock {
  kicker?: string | null;
  heading: string;
  intro?: string | null;
  tone: 'plain' | 'light' | 'dark';
  style: 'raised' | 'flat';
  items?:
    | {
        icon:
          | 'users'
          | 'credit-card'
          | 'life-buoy'
          | 'shield-check'
          | 'mail'
          | 'server'
          | 'lock'
          | 'hard-drive'
          | 'layout-grid'
          | 'boxes'
          | 'sparkles'
          | 'graduation-cap'
          | 'building'
          | 'trending-up'
          | 'handshake'
          | 'globe'
          | 'earth'
          | 'check'
          | 'receipt';
        title: string;
        body?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'featureCards';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ServicesGridBlock".
 */
export interface ServicesGridBlock {
  kicker?: string | null;
  heading: string;
  intro?: string | null;
  tone: 'plain' | 'light' | 'dark';
  /**
   * Optional. Lets a link jump here, e.g. services for /bw#services.
   */
  anchor?: string | null;
  showTaxNote?: boolean | null;
  cards?:
    | {
        icon:
          | 'users'
          | 'credit-card'
          | 'life-buoy'
          | 'shield-check'
          | 'mail'
          | 'server'
          | 'lock'
          | 'hard-drive'
          | 'layout-grid'
          | 'boxes'
          | 'sparkles'
          | 'graduation-cap'
          | 'building'
          | 'trending-up'
          | 'handshake'
          | 'globe'
          | 'earth'
          | 'check'
          | 'receipt';
        title: string;
        body?: string | null;
        note?: string | null;
        dataCentre?: boolean | null;
        /**
         * Tick categories or single products. The lowest live price among them shows in each market.
         */
        products?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  more?: {
    label?: string | null;
    to?: ('market' | 'site' | 'email' | 'thebe') | null;
    /**
     * Starts with /. For this market's pricing page: /pricing
     */
    path?: string | null;
    subject?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'servicesGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PricingBlock".
 */
export interface PricingBlock {
  kicker?: string | null;
  heading: string;
  intro?: string | null;
  tone: 'plain' | 'light' | 'dark';
  /**
   * Tick categories or single products. The lowest live price among them shows in each market.
   */
  products?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  more?: {
    label?: string | null;
    to?: ('market' | 'site' | 'email' | 'thebe') | null;
    /**
     * Starts with /. For this market's pricing page: /pricing
     */
    path?: string | null;
    subject?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'pricing';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PriceTablesBlock".
 */
export interface PriceTablesBlock {
  domainsHeading?: string | null;
  domainsIntro?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'priceTables';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TextBlock".
 */
export interface TextBlock {
  heading?: string | null;
  /**
   * You can write {market}, {currency}, {support-email}, {data-protection-law} or {deletion-notice-days}; the market's own details appear in their place.
   */
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  tone: 'plain' | 'light' | 'dark';
  id?: string | null;
  blockName?: string | null;
  blockType: 'text';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageTextBlock".
 */
export interface ImageTextBlock {
  kicker?: string | null;
  heading: string;
  intro?: string | null;
  tone: 'plain' | 'light' | 'dark';
  points?:
    | {
        icon:
          | 'users'
          | 'credit-card'
          | 'life-buoy'
          | 'shield-check'
          | 'mail'
          | 'server'
          | 'lock'
          | 'hard-drive'
          | 'layout-grid'
          | 'boxes'
          | 'sparkles'
          | 'graduation-cap'
          | 'building'
          | 'trending-up'
          | 'handshake'
          | 'globe'
          | 'earth'
          | 'check'
          | 'receipt';
        title: string;
        body?: string | null;
        id?: string | null;
      }[]
    | null;
  picture: {
    source: 'upload' | 'console-home' | 'console-invoice' | 'thebe-approvals';
    image?: (number | null) | Media;
    caption?: string | null;
  };
  pictureSide: 'right' | 'left';
  /**
   * Optional. Puts the picture in a card with a title, a line and a link.
   */
  card?: {
    kicker?: string | null;
    title?: string | null;
    body?: string | null;
    link?: {
      label?: string | null;
      to?: ('market' | 'site' | 'email' | 'thebe') | null;
      /**
       * Starts with /. For this market's pricing page: /pricing
       */
      path?: string | null;
      subject?: string | null;
    };
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'imageText';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FaqBlock".
 */
export interface FaqBlock {
  kicker?: string | null;
  heading: string;
  intro?: string | null;
  headingPhone?: string | null;
  tone: 'plain' | 'light' | 'dark';
  items?:
    | {
        question: string;
        answer: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        /**
         * Phones show a shorter list, as designed.
         */
        showOnPhone?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * A link to the help centre stays hidden until the help centre has articles.
   */
  more?: {
    label?: string | null;
    to?: ('market' | 'site' | 'email' | 'thebe') | null;
    /**
     * Starts with /. For this market's pricing page: /pricing
     */
    path?: string | null;
    subject?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'faq';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialsBlock".
 */
export interface TestimonialsBlock {
  /**
   * Hidden from view (read by screen readers) when left empty.
   */
  heading?: string | null;
  tone: 'plain' | 'light' | 'dark';
  id?: string | null;
  blockName?: string | null;
  blockType: 'testimonials';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LogoStripBlock".
 */
export interface LogoStripBlock {
  heading?: string | null;
  tone: 'plain' | 'light' | 'dark';
  id?: string | null;
  blockName?: string | null;
  blockType: 'logoStrip';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "InsightsStripBlock".
 */
export interface InsightsStripBlock {
  kicker?: string | null;
  heading: string;
  intro?: string | null;
  headingPhone?: string | null;
  tone: 'plain' | 'light' | 'dark';
  /**
   * Optional. Lets a link jump here, e.g. insights for /bw#insights.
   */
  anchor?: string | null;
  /**
   * Optional. Leave empty for the newest insights on any topic.
   */
  topic?: ('resilience' | 'compliance' | 'email-security' | 'productivity' | 'security' | 'websites') | null;
  more?: {
    label?: string | null;
    to?: ('market' | 'site' | 'email' | 'thebe') | null;
    /**
     * Starts with /. For this market's pricing page: /pricing
     */
    path?: string | null;
    subject?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'insightsStrip';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock".
 */
export interface CallToActionBlock {
  heading: string;
  body?: string | null;
  tone: 'plain' | 'light' | 'dark';
  primary?: {
    label?: string | null;
    to?: ('market' | 'site' | 'email' | 'thebe') | null;
    /**
     * Starts with /. For this market's pricing page: /pricing
     */
    path?: string | null;
    subject?: string | null;
  };
  secondary?: {
    label?: string | null;
    to?: ('market' | 'site' | 'email' | 'thebe') | null;
    /**
     * Starts with /. For this market's pricing page: /pricing
     */
    path?: string | null;
    subject?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'callToAction';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AssistantNoticeBlock".
 */
export interface AssistantNoticeBlock {
  /**
   * The notice itself is a fixed product fact: what the support assistant is sent, and where the AI service runs.
   */
  heading: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'assistantNotice';
}
/**
 * Articles for the Insights strip and page. Each market's version is a language in the switcher at the top; a market without its own words shows Botswana's.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "insights".
 */
export interface Insight {
  id: number;
  title: string;
  /**
   * The article's address: /<market>/insights/<address>, e.g. tested-backups.
   */
  slug: string;
  topic: 'resilience' | 'compliance' | 'email-security' | 'productivity' | 'security' | 'websites';
  /**
   * Set on the first publish. Newest first in the Insights strip.
   */
  publishedAt?: string | null;
  /**
   * Worked out from the article's length.
   */
  readingMinutes?: number | null;
  /**
   * One or two sentences for the Insights strip and search results.
   */
  summary: string;
  image?: (number | null) | Media;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * The product the article ends with. Tick one product.
   */
  related?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  seo?: {
    title?: string | null;
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Answers for customers, grouped by section. Each market's version is a language in the switcher at the top; a market without its own words shows Botswana's.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "help".
 */
export interface Help {
  id: number;
  /**
   * A question or task, e.g. How do I move my email to Microsoft 365?
   */
  title: string;
  /**
   * The article's address: /<market>/help/<address>, e.g. move-your-email.
   */
  slug: string;
  section: 'getting-started' | 'domains' | 'email' | 'websites' | 'security' | 'hosting' | 'billing' | 'account';
  /**
   * Lower numbers come first in their section.
   */
  order?: number | null;
  /**
   * One sentence for the help centre's list and search results.
   */
  summary: string;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Each market's text is a language in the switcher at the top. A market without its own text shows a note that it is on its way, never another market's.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal".
 */
export interface Legal {
  id: number;
  /**
   * Data protection shows on the Security page.
   */
  kind: 'terms' | 'privacy' | 'refunds' | 'service-providers' | 'data-protection';
  title: string;
  /**
   * e.g. Last updated: 29 September 2026
   */
  updated?: string | null;
  /**
   * Shown at the top until the text is approved by legal.
   */
  draftNotice?: string | null;
  /**
   * Only a Publisher can tick this, once a lawyer has approved this market's text. It removes the draft banner when published.
   */
  approvedByLegal?: boolean | null;
  /**
   * You can write {market}, {currency}, {support-email}, {data-protection-law} or {deletion-notice-days}; the market's own details appear in their place.
   */
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Shown on the home page, in the footer and in the Email menu once approved to display. Drag to reorder.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners".
 */
export interface Partner {
  id: number;
  _order?: string | null;
  /**
   * e.g. Microsoft
   */
  name: string;
  /**
   * The words on the badge, exactly as the partner allows, e.g. Microsoft partner.
   */
  badge: string;
  /**
   * The partner's official logo, as a PNG or WebP. Without one the badge shows its wording.
   */
  logo?: (number | null) | Media;
  /**
   * Optional. The partner's page confirming the status, e.g. the partner directory entry.
   */
  link?: string | null;
  /**
   * Optional. The first approved partner marked for email shows there.
   */
  feature?: 'email' | null;
  /**
   * For staff only: where the permission to display this came from (agreement, email, portal page) and when.
   */
  evidence?: string | null;
  /**
   * Tick once the evidence is on file. Only Publishers can change this.
   */
  approved?: boolean | null;
  /**
   * Leave empty to show it in every market.
   */
  markets?: ('bw' | 'za' | 'zw' | 'global')[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * "Businesses we look after" on the home page. Shown only with the client's permission. Drag to reorder.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "client-logos".
 */
export interface ClientLogo {
  id: number;
  _order?: string | null;
  company: string;
  /**
   * Optional. Without a logo the company's name shows.
   */
  logo?: (number | null) | Media;
  website?: string | null;
  /**
   * Tick once the client has agreed in writing. Only Publishers can change this.
   */
  permission?: boolean | null;
  permissionDate?: string | null;
  /**
   * Leave empty to show it in every market.
   */
  markets?: ('bw' | 'za' | 'zw' | 'global')[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * The figures on the home page, e.g. 250+ businesses we look after. Drag to reorder.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "proof-numbers".
 */
export interface ProofNumber {
  id: number;
  _order?: string | null;
  /**
   * The median first reply is worked out from the last 90 days of support tickets, and hides while there are fewer than 30.
   */
  calculated: 'typed' | 'medianFirstReply';
  /**
   * e.g. 250+
   */
  value?: string | null;
  /**
   * e.g. Businesses we look after
   */
  label: string;
  /**
   * For staff only: where the figure comes from and when it was last checked.
   */
  source?: string | null;
  /**
   * Tick once the figure is checked. Only Publishers can change this.
   */
  visible?: boolean | null;
  /**
   * Leave empty to show it in every market.
   */
  markets?: ('bw' | 'za' | 'zw' | 'global')[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * "People you can call by name" on the home page. Shown only with a photo and when visible. Drag to reorder.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members".
 */
export interface TeamMember {
  id: number;
  _order?: string | null;
  /**
   * As they would like it shown, e.g. Naledi K.
   */
  name: string;
  /**
   * e.g. Customer success
   */
  role: string;
  photo?: (number | null) | Media;
  /**
   * Tick once they have agreed to be shown. Only Publishers can change this.
   */
  visible?: boolean | null;
  /**
   * Leave empty to show it in every market.
   */
  markets?: ('bw' | 'za' | 'zw' | 'global')[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Shown by a Testimonials section on any page, only with permission. Drag to reorder.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  _order?: string | null;
  quote: string;
  name: string;
  role?: string | null;
  company?: string | null;
  /**
   * Optional. The company's logo.
   */
  logo?: (number | null) | Media;
  /**
   * Optional. The outcome in a few words, e.g. Moved 40 mailboxes over a weekend.
   */
  result?: string | null;
  /**
   * Tick once the person has agreed to be quoted. Only Publishers can change this.
   */
  permission?: boolean | null;
  /**
   * Leave empty to show it in every market.
   */
  markets?: ('bw' | 'za' | 'zw' | 'global')[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Client websites under "Your website, your way" on the home page, only with permission. Drag to reorder.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "showcase-sites".
 */
export interface ShowcaseSite {
  id: number;
  _order?: string | null;
  client: string;
  /**
   * A screenshot of the home page, about 1440 by 900.
   */
  screenshot: number | Media;
  /**
   * e.g. Law firm
   */
  industry?: string | null;
  /**
   * The live site, starting with https://
   */
  url?: string | null;
  /**
   * Tick once the client has agreed. Only Publishers can change this.
   */
  permission?: boolean | null;
  /**
   * Leave empty to show it in every market.
   */
  markets?: ('bw' | 'za' | 'zw' | 'global')[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Website roles are set on the Staff page in the staff console.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "staff".
 */
export interface Staff {
  id: number;
  consoleUserId: string;
  name: string;
  email: string;
  websiteRole: 'EDITOR' | 'PUBLISHER';
  updatedAt: string;
  createdAt: string;
  collection: 'staff';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'insights';
        value: number | Insight;
      } | null)
    | ({
        relationTo: 'help';
        value: number | Help;
      } | null)
    | ({
        relationTo: 'legal';
        value: number | Legal;
      } | null)
    | ({
        relationTo: 'partners';
        value: number | Partner;
      } | null)
    | ({
        relationTo: 'client-logos';
        value: number | ClientLogo;
      } | null)
    | ({
        relationTo: 'proof-numbers';
        value: number | ProofNumber;
      } | null)
    | ({
        relationTo: 'team-members';
        value: number | TeamMember;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'showcase-sites';
        value: number | ShowcaseSite;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'staff';
        value: number | Staff;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'staff';
    value: number | Staff;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'staff';
    value: number | Staff;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  style?: T;
  layout?:
    | T
    | {
        homeHero?: T | HomeHeroBlockSelect<T>;
        domainStore?: T | DomainStoreBlockSelect<T>;
        proofStrip?: T | ProofStripBlockSelect<T>;
        numberedServices?: T | NumberedServicesBlockSelect<T>;
        whoWeHelp?: T | WhoWeHelpBlockSelect<T>;
        emailShowcase?: T | EmailShowcaseBlockSelect<T>;
        websitesShowcase?: T | WebsitesShowcaseBlockSelect<T>;
        securityPanel?: T | SecurityPanelBlockSelect<T>;
        thebeSection?: T | ThebeSectionBlockSelect<T>;
        plansTable?: T | PlansTableBlockSelect<T>;
        compareTable?: T | CompareTableBlockSelect<T>;
        teamSection?: T | TeamSectionBlockSelect<T>;
        closingBanner?: T | ClosingBannerBlockSelect<T>;
        pageIntro?: T | PageIntroBlockSelect<T>;
        hero?: T | HeroBlockSelect<T>;
        domainSearch?: T | DomainSearchBlockSelect<T>;
        featureCards?: T | FeatureCardsBlockSelect<T>;
        servicesGrid?: T | ServicesGridBlockSelect<T>;
        pricing?: T | PricingBlockSelect<T>;
        priceTables?: T | PriceTablesBlockSelect<T>;
        text?: T | TextBlockSelect<T>;
        imageText?: T | ImageTextBlockSelect<T>;
        faq?: T | FaqBlockSelect<T>;
        testimonials?: T | TestimonialsBlockSelect<T>;
        logoStrip?: T | LogoStripBlockSelect<T>;
        insightsStrip?: T | InsightsStripBlockSelect<T>;
        callToAction?: T | CallToActionBlockSelect<T>;
        assistantNotice?: T | AssistantNoticeBlockSelect<T>;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HomeHeroBlock_select".
 */
export interface HomeHeroBlockSelect<T extends boolean = true> {
  kicker?: T;
  heading?: T;
  sub?: T;
  subPhone?: T;
  supporting?: T;
  primary?:
    | T
    | {
        label?: T;
        to?: T;
        path?: T;
        subject?: T;
      };
  secondary?:
    | T
    | {
        label?: T;
        to?: T;
        path?: T;
        subject?: T;
      };
  showConsole?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DomainStoreBlock_select".
 */
export interface DomainStoreBlockSelect<T extends boolean = true> {
  anchor?: T;
  kicker?: T;
  heading?: T;
  headingPhone?: T;
  intro?: T;
  introPhone?: T;
  example?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProofStripBlock_select".
 */
export interface ProofStripBlockSelect<T extends boolean = true> {
  anchor?: T;
  numbers?: T;
  partnersHeading?: T;
  clientsHeading?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "NumberedServicesBlock_select".
 */
export interface NumberedServicesBlockSelect<T extends boolean = true> {
  anchor?: T;
  kicker?: T;
  heading?: T;
  headingPhone?: T;
  items?:
    | T
    | {
        title?: T;
        body?: T;
        bodyPhone?: T;
        link?:
          | T
          | {
              label?: T;
              to?: T;
              path?: T;
              subject?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WhoWeHelpBlock_select".
 */
export interface WhoWeHelpBlockSelect<T extends boolean = true> {
  anchor?: T;
  kicker?: T;
  heading?: T;
  headingPhone?: T;
  intro?: T;
  introPhone?: T;
  items?:
    | T
    | {
        title?: T;
        body?: T;
        bodyPhone?: T;
        id?: T;
      };
  approved?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EmailShowcaseBlock_select".
 */
export interface EmailShowcaseBlockSelect<T extends boolean = true> {
  anchor?: T;
  kicker?: T;
  heading?: T;
  headingPhone?: T;
  intro?: T;
  introPhone?: T;
  caption?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WebsitesShowcaseBlock_select".
 */
export interface WebsitesShowcaseBlockSelect<T extends boolean = true> {
  anchor?: T;
  kicker?: T;
  heading?: T;
  headingPhone?: T;
  intro?: T;
  introPhone?: T;
  cards?:
    | T
    | {
        title?: T;
        body?: T;
        bodyPhone?: T;
        link?:
          | T
          | {
              label?: T;
              to?: T;
              path?: T;
              subject?: T;
            };
        products?: T;
        id?: T;
      };
  industries?:
    | T
    | {
        name?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SecurityPanelBlock_select".
 */
export interface SecurityPanelBlockSelect<T extends boolean = true> {
  anchor?: T;
  kicker?: T;
  heading?: T;
  headingPhone?: T;
  intro?: T;
  introPhone?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ThebeSectionBlock_select".
 */
export interface ThebeSectionBlockSelect<T extends boolean = true> {
  anchor?: T;
  kicker?: T;
  heading?: T;
  headingPhone?: T;
  intro?: T;
  introPhone?: T;
  kickerPhone?: T;
  features?:
    | T
    | {
        title?: T;
        body?: T;
        accounting?: T;
        id?: T;
      };
  showAccounting?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PlansTableBlock_select".
 */
export interface PlansTableBlockSelect<T extends boolean = true> {
  anchor?: T;
  kicker?: T;
  heading?: T;
  headingPhone?: T;
  intro?: T;
  introPhone?: T;
  rows?:
    | T
    | {
        label?: T;
        labelPhone?: T;
        start?: T;
        startPhone?: T;
        startIncluded?: T;
        grow?: T;
        growPhone?: T;
        growIncluded?: T;
        protect?: T;
        protectPhone?: T;
        protectIncluded?: T;
        id?: T;
      };
  footnote?: T;
  users?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CompareTableBlock_select".
 */
export interface CompareTableBlockSelect<T extends boolean = true> {
  anchor?: T;
  kicker?: T;
  heading?: T;
  headingPhone?: T;
  freeHeading?: T;
  usHeading?: T;
  rows?:
    | T
    | {
        label?: T;
        free?: T;
        us?: T;
        labelPhone?: T;
        freePhone?: T;
        usPhone?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TeamSectionBlock_select".
 */
export interface TeamSectionBlockSelect<T extends boolean = true> {
  anchor?: T;
  kicker?: T;
  heading?: T;
  headingPhone?: T;
  intro?: T;
  introPhone?: T;
  link?:
    | T
    | {
        label?: T;
        to?: T;
        path?: T;
        subject?: T;
      };
  nsmc?:
    | T
    | {
        lead?: T;
        text?: T;
        leadPhone?: T;
        textPhone?: T;
        linkLabel?: T;
      };
  replyLine?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ClosingBannerBlock_select".
 */
export interface ClosingBannerBlockSelect<T extends boolean = true> {
  heading?: T;
  primary?:
    | T
    | {
        label?: T;
        to?: T;
        path?: T;
        subject?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PageIntroBlock_select".
 */
export interface PageIntroBlockSelect<T extends boolean = true> {
  kicker?: T;
  heading?: T;
  intro?: T;
  showTaxNote?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock_select".
 */
export interface HeroBlockSelect<T extends boolean = true> {
  kicker?: T;
  heading?: T;
  sub?: T;
  primary?:
    | T
    | {
        label?: T;
        to?: T;
        path?: T;
        subject?: T;
      };
  secondary?:
    | T
    | {
        label?: T;
        to?: T;
        path?: T;
        subject?: T;
      };
  supporting?:
    | T
    | {
        text?: T;
        id?: T;
      };
  picture?:
    | T
    | {
        source?: T;
        image?: T;
        caption?: T;
      };
  domainSearch?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DomainSearchBlock_select".
 */
export interface DomainSearchBlockSelect<T extends boolean = true> {
  heading?: T;
  intro?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeatureCardsBlock_select".
 */
export interface FeatureCardsBlockSelect<T extends boolean = true> {
  kicker?: T;
  heading?: T;
  intro?: T;
  tone?: T;
  style?: T;
  items?:
    | T
    | {
        icon?: T;
        title?: T;
        body?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ServicesGridBlock_select".
 */
export interface ServicesGridBlockSelect<T extends boolean = true> {
  kicker?: T;
  heading?: T;
  intro?: T;
  tone?: T;
  anchor?: T;
  showTaxNote?: T;
  cards?:
    | T
    | {
        icon?: T;
        title?: T;
        body?: T;
        note?: T;
        dataCentre?: T;
        products?: T;
        id?: T;
      };
  more?:
    | T
    | {
        label?: T;
        to?: T;
        path?: T;
        subject?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PricingBlock_select".
 */
export interface PricingBlockSelect<T extends boolean = true> {
  kicker?: T;
  heading?: T;
  intro?: T;
  tone?: T;
  products?: T;
  more?:
    | T
    | {
        label?: T;
        to?: T;
        path?: T;
        subject?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PriceTablesBlock_select".
 */
export interface PriceTablesBlockSelect<T extends boolean = true> {
  domainsHeading?: T;
  domainsIntro?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TextBlock_select".
 */
export interface TextBlockSelect<T extends boolean = true> {
  heading?: T;
  body?: T;
  tone?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageTextBlock_select".
 */
export interface ImageTextBlockSelect<T extends boolean = true> {
  kicker?: T;
  heading?: T;
  intro?: T;
  tone?: T;
  points?:
    | T
    | {
        icon?: T;
        title?: T;
        body?: T;
        id?: T;
      };
  picture?:
    | T
    | {
        source?: T;
        image?: T;
        caption?: T;
      };
  pictureSide?: T;
  card?:
    | T
    | {
        kicker?: T;
        title?: T;
        body?: T;
        link?:
          | T
          | {
              label?: T;
              to?: T;
              path?: T;
              subject?: T;
            };
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FaqBlock_select".
 */
export interface FaqBlockSelect<T extends boolean = true> {
  kicker?: T;
  heading?: T;
  intro?: T;
  headingPhone?: T;
  tone?: T;
  items?:
    | T
    | {
        question?: T;
        answer?: T;
        showOnPhone?: T;
        id?: T;
      };
  more?:
    | T
    | {
        label?: T;
        to?: T;
        path?: T;
        subject?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialsBlock_select".
 */
export interface TestimonialsBlockSelect<T extends boolean = true> {
  heading?: T;
  tone?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LogoStripBlock_select".
 */
export interface LogoStripBlockSelect<T extends boolean = true> {
  heading?: T;
  tone?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "InsightsStripBlock_select".
 */
export interface InsightsStripBlockSelect<T extends boolean = true> {
  kicker?: T;
  heading?: T;
  intro?: T;
  headingPhone?: T;
  tone?: T;
  anchor?: T;
  topic?: T;
  more?:
    | T
    | {
        label?: T;
        to?: T;
        path?: T;
        subject?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock_select".
 */
export interface CallToActionBlockSelect<T extends boolean = true> {
  heading?: T;
  body?: T;
  tone?: T;
  primary?:
    | T
    | {
        label?: T;
        to?: T;
        path?: T;
        subject?: T;
      };
  secondary?:
    | T
    | {
        label?: T;
        to?: T;
        path?: T;
        subject?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AssistantNoticeBlock_select".
 */
export interface AssistantNoticeBlockSelect<T extends boolean = true> {
  heading?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "insights_select".
 */
export interface InsightsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  topic?: T;
  publishedAt?: T;
  readingMinutes?: T;
  summary?: T;
  image?: T;
  body?: T;
  related?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "help_select".
 */
export interface HelpSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  section?: T;
  order?: T;
  summary?: T;
  body?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal_select".
 */
export interface LegalSelect<T extends boolean = true> {
  kind?: T;
  title?: T;
  updated?: T;
  draftNotice?: T;
  approvedByLegal?: T;
  body?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners_select".
 */
export interface PartnersSelect<T extends boolean = true> {
  _order?: T;
  name?: T;
  badge?: T;
  logo?: T;
  link?: T;
  feature?: T;
  evidence?: T;
  approved?: T;
  markets?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "client-logos_select".
 */
export interface ClientLogosSelect<T extends boolean = true> {
  _order?: T;
  company?: T;
  logo?: T;
  website?: T;
  permission?: T;
  permissionDate?: T;
  markets?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "proof-numbers_select".
 */
export interface ProofNumbersSelect<T extends boolean = true> {
  _order?: T;
  calculated?: T;
  value?: T;
  label?: T;
  source?: T;
  visible?: T;
  markets?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members_select".
 */
export interface TeamMembersSelect<T extends boolean = true> {
  _order?: T;
  name?: T;
  role?: T;
  photo?: T;
  visible?: T;
  markets?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  _order?: T;
  quote?: T;
  name?: T;
  role?: T;
  company?: T;
  logo?: T;
  result?: T;
  permission?: T;
  markets?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "showcase-sites_select".
 */
export interface ShowcaseSitesSelect<T extends boolean = true> {
  _order?: T;
  client?: T;
  screenshot?: T;
  industry?: T;
  url?: T;
  permission?: T;
  markets?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        share?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "staff_select".
 */
export interface StaffSelect<T extends boolean = true> {
  consoleUserId?: T;
  name?: T;
  email?: T;
  websiteRole?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * The menus at the top of every public page. Each menu opens full width on wide screens and as a list on phones.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  /**
   * In the order they appear. A menu with no links showing in a market is left out there.
   */
  menus?:
    | {
        label: string;
        right?: boolean | null;
        columns?:
          | {
              /**
               * Optional.
               */
              heading?: string | null;
              links?:
                | {
                    link: {
                      label: string;
                      to?: ('market' | 'site' | 'email' | 'thebe') | null;
                      /**
                       * Starts with /. For this market's pricing page: /pricing
                       */
                      path?: string | null;
                      subject?: string | null;
                    };
                    description?: string | null;
                    /**
                     * Optional. Tick the products the link is about: it shows only while one of them is live and priced in the market.
                     */
                    products?:
                      | {
                          [k: string]: unknown;
                        }
                      | unknown[]
                      | string
                      | number
                      | boolean
                      | null;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[]
          | null;
        feature?: {
          /**
           * Optional. Each kind hides itself when it has nothing approved to show.
           */
          kind?: ('domainSearch' | 'partnerBadge' | 'websitePreview' | 'thebe' | 'support' | 'note') | null;
          heading?: string | null;
          text?: string | null;
          link?: {
            label?: string | null;
            to?: ('market' | 'site' | 'email' | 'thebe') | null;
            /**
             * Starts with /. For this market's pricing page: /pricing
             */
            path?: string | null;
            subject?: string | null;
          };
        };
        id?: string | null;
      }[]
    | null;
  /**
   * Plain links after the menus, e.g. Plans. A link about products shows only while one of them is on sale.
   */
  links?:
    | {
        link: {
          label: string;
          to?: ('market' | 'site' | 'email' | 'thebe') | null;
          /**
           * Starts with /. For this market's pricing page: /pricing
           */
          path?: string | null;
          subject?: string | null;
        };
        description?: string | null;
        /**
         * Optional. Tick the products the link is about: it shows only while one of them is live and priced in the market.
         */
        products?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The links and words at the bottom of every public page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  /**
   * The sign-up across the top of the footer. It hides when the heading is empty.
   */
  newsletter?: {
    heading?: string | null;
    text?: string | null;
  };
  /**
   * Under the logo. A second line is fine, e.g. Looking after businesses since 2014.
   */
  tagline?: string | null;
  columns?:
    | {
        heading: string;
        links?:
          | {
              link: {
                label: string;
                to?: ('market' | 'site' | 'email' | 'thebe') | null;
                /**
                 * Starts with /. For this market's pricing page: /pricing
                 */
                path?: string | null;
                subject?: string | null;
              };
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Leave email, phone or hours empty to use the market's own settings in the staff console. Anything else left empty stays hidden.
   */
  contact?: {
    email?: string | null;
    phone?: string | null;
    /**
     * Shows a WhatsApp link with the social links.
     */
    whatsapp?: string | null;
    hours?: string | null;
    address?: string | null;
  };
  /**
   * Each shows only when it has an address.
   */
  social?: {
    linkedin?: string | null;
    facebook?: string | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * One line above the top of every public page, between the start and end below. Leave the text empty for none.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "announcement".
 */
export interface Announcement {
  id: number;
  /**
   * e.g. Our offices are closed on 30 September. Urgent issues are still watched around the clock.
   */
  text?: string | null;
  link?: {
    label?: string | null;
    to?: ('market' | 'site' | 'email' | 'thebe') | null;
    /**
     * Starts with /. For this market's pricing page: /pricing
     */
    path?: string | null;
    subject?: string | null;
  };
  /**
   * Empty shows it straight away.
   */
  startsAt?: string | null;
  /**
   * Empty keeps it up until it is removed.
   */
  endsAt?: string | null;
  /**
   * Leave empty to show it in every market.
   */
  markets?: ('bw' | 'za' | 'zw' | 'global')[] | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The AI assistant on every public page. Each market has its own greeting, quick replies and extra knowledge (switch market at the top).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sales-assistant".
 */
export interface SalesAssistant {
  id: number;
  /**
   * Thapelo shows in every market except these.
   */
  off?: ('bw' | 'za' | 'zw' | 'global')[] | null;
  /**
   * Thapelo's first message. Leave empty for: Hi, I'm Thapelo. I can help you find a domain, choose a plan or move your email. What does your business do?
   */
  greeting?: string | null;
  /**
   * Buttons under the greeting that send their words as the visitor's question. "Talk to a person" is always added. Leave empty for: Find a domain, Compare plans, Move my email.
   */
  quickReplies?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Facts Thapelo may use on top of the catalogue, price books, help centre and insights, e.g. opening hours or how moving email works. Plain statements only. Thapelo treats this as information, never as instructions, and it can't hold prices.
   */
  knowledge?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Where the Try Thebe buttons go. Changes go live on saving.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partner-links".
 */
export interface PartnerLink {
  id: number;
  /**
   * Thebe's sign-up page, once it exists, e.g. https://www.thebe.africa/sign-up. Leave empty for Thebe's website, https://www.thebe.africa.
   */
  thebeTryUrl?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  menus?:
    | T
    | {
        label?: T;
        right?: T;
        columns?:
          | T
          | {
              heading?: T;
              links?:
                | T
                | {
                    link?:
                      | T
                      | {
                          label?: T;
                          to?: T;
                          path?: T;
                          subject?: T;
                        };
                    description?: T;
                    products?: T;
                    id?: T;
                  };
              id?: T;
            };
        feature?:
          | T
          | {
              kind?: T;
              heading?: T;
              text?: T;
              link?:
                | T
                | {
                    label?: T;
                    to?: T;
                    path?: T;
                    subject?: T;
                  };
            };
        id?: T;
      };
  links?:
    | T
    | {
        link?:
          | T
          | {
              label?: T;
              to?: T;
              path?: T;
              subject?: T;
            };
        description?: T;
        products?: T;
        id?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  newsletter?:
    | T
    | {
        heading?: T;
        text?: T;
      };
  tagline?: T;
  columns?:
    | T
    | {
        heading?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    label?: T;
                    to?: T;
                    path?: T;
                    subject?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  contact?:
    | T
    | {
        email?: T;
        phone?: T;
        whatsapp?: T;
        hours?: T;
        address?: T;
      };
  social?:
    | T
    | {
        linkedin?: T;
        facebook?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "announcement_select".
 */
export interface AnnouncementSelect<T extends boolean = true> {
  text?: T;
  link?:
    | T
    | {
        label?: T;
        to?: T;
        path?: T;
        subject?: T;
      };
  startsAt?: T;
  endsAt?: T;
  markets?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sales-assistant_select".
 */
export interface SalesAssistantSelect<T extends boolean = true> {
  off?: T;
  greeting?: T;
  quickReplies?:
    | T
    | {
        label?: T;
        id?: T;
      };
  knowledge?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partner-links_select".
 */
export interface PartnerLinksSelect<T extends boolean = true> {
  thebeTryUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'insights';
          value: number | Insight;
        } | null)
      | ({
          relationTo: 'help';
          value: number | Help;
        } | null)
      | ({
          relationTo: 'legal';
          value: number | Legal;
        } | null);
    global?: ('header' | 'footer') | null;
    user?: {
      relationTo: 'staff';
      value: number | Staff;
    } | null;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}